<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        collect([
        ['number' => 1, 'name' => 'Al-Fatihah', 'ayah_count' => 7],
        ['number' => 2, 'name' => 'Al-Baqarah', 'ayah_count' => 286],
        ['number' => 3, 'name' => 'Ali Imran', 'ayah_count' => 200],
        ['number' => 4, 'name' => 'An-Nisa', 'ayah_count' => 176],
        ['number' => 5, 'name' => 'Al-Ma\'idah', 'ayah_count' => 120],
        ['number' => 6, 'name' => 'Al-An\'am', 'ayah_count' => 165],
        ['number' => 7, 'name' => 'Al-A\'raf', 'ayah_count' => 206],
        ['number' => 8, 'name' => 'Al-Anfal', 'ayah_count' => 75],
        ['number' => 9, 'name' => 'At-Taubah', 'ayah_count' => 129],
        ['number' => 10, 'name' => 'Yunus', 'ayah_count' => 109],
        ['number' => 11, 'name' => 'Hud', 'ayah_count' => 123],
        ['number' => 12, 'name' => 'Yusuf', 'ayah_count' => 111],
        ['number' => 13, 'name' => 'Ar-Ra\'d', 'ayah_count' => 43],
        ['number' => 14, 'name' => 'Ibrahim', 'ayah_count' => 52],
        ['number' => 15, 'name' => 'Al-Hijr', 'ayah_count' => 99],
        ['number' => 16, 'name' => 'An-Nahl', 'ayah_count' => 128],
        ['number' => 17, 'name' => 'Al-Isra', 'ayah_count' => 111],
        ['number' => 18, 'name' => 'Al-Kahf', 'ayah_count' => 110],
        ['number' => 19, 'name' => 'Maryam', 'ayah_count' => 98],
        ['number' => 20, 'name' => 'Taha', 'ayah_count' => 135],
        ['number' => 21, 'name' => 'Al-Anbiya', 'ayah_count' => 112],
        ['number' => 22, 'name' => 'Al-Hajj', 'ayah_count' => 78],
        ['number' => 23, 'name' => 'Al-Mu\'minun', 'ayah_count' => 118],
        ['number' => 24, 'name' => 'An-Nur', 'ayah_count' => 64],
        ['number' => 25, 'name' => 'Al-Furqan', 'ayah_count' => 77],
        ['number' => 26, 'name' => 'Ash-Shu\'ara', 'ayah_count' => 227],
        ['number' => 27, 'name' => 'An-Naml', 'ayah_count' => 93],
        ['number' => 28, 'name' => 'Al-Qasas', 'ayah_count' => 88],
        ['number' => 29, 'name' => 'Al-Ankabut', 'ayah_count' => 69],
        ['number' => 30, 'name' => 'Ar-Rum', 'ayah_count' => 60],
        ['number' => 31, 'name' => 'Luqman', 'ayah_count' => 34],
        ['number' => 32, 'name' => 'As-Sajdah', 'ayah_count' => 30],
        ['number' => 33, 'name' => 'Al-Ahzab', 'ayah_count' => 73],
        ['number' => 34, 'name' => 'Saba', 'ayah_count' => 54],
        ['number' => 35, 'name' => 'Fatir', 'ayah_count' => 45],
        ['number' => 36, 'name' => 'Ya-Sin', 'ayah_count' => 83],
        ['number' => 37, 'name' => 'As-Saffat', 'ayah_count' => 182],
        ['number' => 38, 'name' => 'Sad', 'ayah_count' => 88],
        ['number' => 39, 'name' => 'Az-Zumar', 'ayah_count' => 75],
        ['number' => 40, 'name' => 'Ghafir', 'ayah_count' => 85],
        ['number' => 41, 'name' => 'Fussilat', 'ayah_count' => 54],
        ['number' => 42, 'name' => 'Ash-Shura', 'ayah_count' => 53],
        ['number' => 43, 'name' => 'Az-Zukhruf', 'ayah_count' => 89],
        ['number' => 44, 'name' => 'Ad-Dukhan', 'ayah_count' => 59],
        ['number' => 45, 'name' => 'Al-Jathiyah', 'ayah_count' => 37],
        ['number' => 46, 'name' => 'Al-Ahqaf', 'ayah_count' => 35],
        ['number' => 47, 'name' => 'Muhammad', 'ayah_count' => 38],
        ['number' => 48, 'name' => 'Al-Fath', 'ayah_count' => 29],
        ['number' => 49, 'name' => 'Al-Hujurat', 'ayah_count' => 18],
        ['number' => 50, 'name' => 'Qaf', 'ayah_count' => 45],
        ['number' => 51, 'name' => 'Adh-Dhariyat', 'ayah_count' => 60],
        ['number' => 52, 'name' => 'At-Tur', 'ayah_count' => 49],
        ['number' => 53, 'name' => 'An-Najm', 'ayah_count' => 62],
        ['number' => 54, 'name' => 'Al-Qamar', 'ayah_count' => 55],
        ['number' => 55, 'name' => 'Ar-Rahman', 'ayah_count' => 78],
        ['number' => 56, 'name' => 'Al-Waqi\'ah', 'ayah_count' => 96],
        ['number' => 57, 'name' => 'Al-Hadid', 'ayah_count' => 29],
        ['number' => 58, 'name' => 'Al-Mujadilah', 'ayah_count' => 22],
        ['number' => 59, 'name' => 'Al-Hashr', 'ayah_count' => 24],
        ['number' => 60, 'name' => 'Al-Mumtahanah', 'ayah_count' => 13],
        ['number' => 61, 'name' => 'As-Saff', 'ayah_count' => 14],
        ['number' => 62, 'name' => 'Al-Jumu\'ah', 'ayah_count' => 11],
        ['number' => 63, 'name' => 'Al-Munafiqun', 'ayah_count' => 11],
        ['number' => 64, 'name' => 'At-Taghabun', 'ayah_count' => 18],
        ['number' => 65, 'name' => 'At-Talaq', 'ayah_count' => 12],
        ['number' => 66, 'name' => 'At-Tahrim', 'ayah_count' => 12],
        ['number' => 67, 'name' => 'Al-Mulk', 'ayah_count' => 30],
        ['number' => 68, 'name' => 'Al-Qalam', 'ayah_count' => 52],
        ['number' => 69, 'name' => 'Al-Haqqah', 'ayah_count' => 52],
        ['number' => 70, 'name' => 'Al-Ma\'arij', 'ayah_count' => 44],
        ['number' => 71, 'name' => 'Nuh', 'ayah_count' => 28],
        ['number' => 72, 'name' => 'Al-Jinn', 'ayah_count' => 28],
        ['number' => 73, 'name' => 'Al-Muzzammil', 'ayah_count' => 20],
        ['number' => 74, 'name' => 'Al-Muddaththir', 'ayah_count' => 56],
        ['number' => 75, 'name' => 'Al-Qiyamah', 'ayah_count' => 40],
        ['number' => 76, 'name' => 'Al-Insan', 'ayah_count' => 31],
        ['number' => 77, 'name' => 'Al-Mursalat', 'ayah_count' => 50],
        ['number' => 78, 'name' => 'An-Naba', 'ayah_count' => 40],
        ['number' => 79, 'name' => 'An-Nazi\'at', 'ayah_count' => 46],
        ['number' => 80, 'name' => 'Abasa', 'ayah_count' => 42],
        ['number' => 81, 'name' => 'At-Takwir', 'ayah_count' => 29],
        ['number' => 82, 'name' => 'Al-Infitar', 'ayah_count' => 19],
        ['number' => 83, 'name' => 'Al-Mutaffifin', 'ayah_count' => 36],
        ['number' => 84, 'name' => 'Al-Inshiqaq', 'ayah_count' => 25],
        ['number' => 85, 'name' => 'Al-Buruj', 'ayah_count' => 22],
        ['number' => 86, 'name' => 'At-Tariq', 'ayah_count' => 17],
        ['number' => 87, 'name' => 'Al-A\'la', 'ayah_count' => 19],
        ['number' => 88, 'name' => 'Al-Ghashiyah', 'ayah_count' => 26],
        ['number' => 89, 'name' => 'Al-Fajr', 'ayah_count' => 30],
        ['number' => 90, 'name' => 'Al-Balad', 'ayah_count' => 20],
        ['number' => 91, 'name' => 'Ash-Shams', 'ayah_count' => 15],
        ['number' => 92, 'name' => 'Al-Lail', 'ayah_count' => 21],
        ['number' => 93, 'name' => 'Ad-Duha', 'ayah_count' => 11],
        ['number' => 94, 'name' => 'Ash-Sharh', 'ayah_count' => 8],
        ['number' => 95, 'name' => 'At-Tin', 'ayah_count' => 8],
        ['number' => 96, 'name' => 'Al-Alaq', 'ayah_count' => 19],
        ['number' => 97, 'name' => 'Al-Qadr', 'ayah_count' => 5],
        ['number' => 98, 'name' => 'Al-Bayyinah', 'ayah_count' => 8],
        ['number' => 99, 'name' => 'Az-Zalzalah', 'ayah_count' => 8],
        ['number' => 100, 'name' => 'Al-Adiyat', 'ayah_count' => 11],
        ['number' => 101, 'name' => 'Al-Qari\'ah', 'ayah_count' => 11],
        ['number' => 102, 'name' => 'At-Takathur', 'ayah_count' => 8],
        ['number' => 103, 'name' => 'Al-Asr', 'ayah_count' => 3],
        ['number' => 104, 'name' => 'Al-Humazah', 'ayah_count' => 9],
        ['number' => 105, 'name' => 'Al-Fil', 'ayah_count' => 5],
        ['number' => 106, 'name' => 'Quraysh', 'ayah_count' => 4],
        ['number' => 107, 'name' => 'Al-Ma\'un', 'ayah_count' => 7],
        ['number' => 108, 'name' => 'Al-Kawthar', 'ayah_count' => 3],
        ['number' => 109, 'name' => 'Al-Kafirun', 'ayah_count' => 6],
        ['number' => 110, 'name' => 'An-Nasr', 'ayah_count' => 3],
        ['number' => 111, 'name' => 'Al-Masad', 'ayah_count' => 5],
        ['number' => 112, 'name' => 'Al-Ikhlas', 'ayah_count' => 4],
        ['number' => 113, 'name' => 'Al-Falaq', 'ayah_count' => 5],
        ['number' => 114, 'name' => 'An-Nas', 'ayah_count' => 6],
        ])->each(fn (array $surah) => Surah::updateOrCreate(
            ['number' => $surah['number']],
            $surah,
        ));
    }
}
